import { ServiceItem, ClientReview, SpinSegment, ConcertItem } from "./types";

export const SERVICES: ServiceItem[] = [
  {
    id: "general-srv",
    title: "General Aircon Servicing",
    description: "Multi-point inspection, filter cleaning, evaporator cleaning, drain pan flushing, and system pressure checks for ice-cold air.",
    price: "SAR 150",
    duration: "45 mins",
    spinProne: true,
  },
  {
    id: "chemical-wash",
    title: "Aircon Chemical Wash",
    description: "Deep chemical flushing of coils, blower wheel, and pipe lines to eliminate persistent blockages and restore cooling power like new.",
    price: "SAR 350",
    duration: "1.5 hours",
    spinProne: true,
  },
  {
    id: "installation-rep",
    title: "Installation & Repair Specialists",
    description: "Expert installation of premium energy-saving units, comprehensive ductwork, and structural diagnostics with certified technicians.",
    price: "Custom Quote",
    duration: "Varies",
    spinProne: false,
  },
  {
    id: "interior-consult",
    title: "Interior Design Consultations",
    description: "Bespoke spatial design, high-fidelity 3D modeling, material sourcing, and end-to-end renovation supervision for residential & commercial premises.",
    price: "FREE (Initial)",
    duration: "1 hour",
    spinProne: true,
  },
];

export const HAPPY_CLIENTS: ClientReview[] = [
  {
    id: "client-1",
    name: "Abdulaziz Al-Otaibi",
    location: "Riyadh",
    avatarLetter: "A",
    colorClass: "bg-red-500",
    rating: 5,
    reviewText: "Amazing fast response! My living room split system started dripping on a hot afternoon. The technician arrived in less than an hour and fixed it perfectly.",
    serviceReceived: "General Aircon Servicing",
  },
  {
    id: "client-2",
    name: "Sarah Al-Mansoori",
    location: "Jeddah",
    avatarLetter: "S",
    colorClass: "bg-amber-500",
    rating: 5,
    reviewText: "Fully trusted partner for spatial upgrades. They completely transformed our office lobby in Jeddah into a highly functional and modern space.",
    serviceReceived: "Interior Design",
  },
  {
    id: "client-3",
    name: "Fahad Al-Kassab",
    location: "Dammam",
    avatarLetter: "F",
    colorClass: "bg-emerald-500",
    rating: 5,
    reviewText: "The chemical wash yielded deep results. The aircon feels pristine and runs with 40% less energy consumption. Excellent transparent rates.",
    serviceReceived: "AC Chemical Wash",
  },
  {
    id: "client-4",
    name: "Reem Al-Sharif",
    location: "Al Khobar",
    avatarLetter: "R",
    colorClass: "bg-blue-500",
    rating: 5,
    reviewText: "Certified, polite technicians who take double care to clean up after work. No surprise fees. Will definitely book long-term maintenance contracts.",
    serviceReceived: "Aircon Maintenance",
  },
  {
    id: "client-5",
    name: "Khalid Bin-Waleed",
    location: "Medina",
    avatarLetter: "K",
    colorClass: "bg-indigo-500",
    rating: 5,
    reviewText: "Outstanding craftsmanship! The local Islamic geometric elements blended elegantly into our villa's luxury guest salon. Brilliant work.",
    serviceReceived: "Luxury Villa Redesign",
  },
  {
    id: "client-6",
    name: "Noura Al-Ghamdi",
    location: "Mecca",
    avatarLetter: "N",
    colorClass: "bg-purple-500",
    rating: 5,
    reviewText: "Helped our retail store stay fully air-conditioned and comfortable through peak shopping seasons. Professionalism at its finest.",
    serviceReceived: "Commercial VRV Install",
  },
  {
    id: "client-7",
    name: "Tariq Yahya",
    location: "Tabuk",
    avatarLetter: "T",
    colorClass: "bg-pink-500",
    rating: 5,
    reviewText: "Fast diagnostics of a faulty compressor motor. Solved with official replacement parts inside a single visit. Guaranteed peace of mind.",
    serviceReceived: "Compressor Replacement",
  },
  {
    id: "client-8",
    name: "Layan Jameel",
    location: "Riyadh",
    avatarLetter: "L",
    colorClass: "bg-cyan-500",
    rating: 5,
    reviewText: "Designed our newly opened boutique bakery. Customer dwell-time has doubled thanks to the gorgeous cozy interior. Masterpiece planning!",
    serviceReceived: "Boutique Space Planning",
  },
];

export const SPIN_SEGMENTS: SpinSegment[] = [
  { id: 0, label: "Free AC Service", color: "#EF4444", value: "Free General Servicing" },
  { id: 1, label: "15% off Design", color: "#F59E0B", value: "15% discount on Interior design" },
  { id: 2, label: "VIP Concert Entry", color: "#10B981", value: "Riyadh Concert Raffle Entry" },
  { id: 3, label: "$50 Aircon Coupon", color: "#3B82F6", value: "SAR 200 Aircon Coupon" },
  { id: 4, label: "Free Consultancy", color: "#6366F1", value: "Free 1-Hour Premium On-Site Audit" },
  { id: 5, label: "20% off Clean", color: "#8B5CF6", value: "20% discount on Chemical Wash" },
  { id: 6, label: "Cashback Voucher", color: "#EC4899", value: "SAR 100 Instant Cashback Offer" },
  { id: 7, label: "Try Again!", color: "#6B7280", value: "Try again for luck!" },
];

export const CONCERTS: ConcertItem[] = [
  {
    id: "concert-1",
    title: "Saudi Investment Classical Gala",
    date: "June 15, 2026",
    time: "20:00 - 23:00",
    venue: "King Fahd Cultural Center, Riyadh",
    price: "Sponsored (Free Entries via Spin)",
    availableTickets: 35,
    description: "An evocative evening of premium orchestral melodies blending authentic Arabic instruments with world-class classical strings.",
  },
  {
    id: "concert-2",
    title: "Jeddah Seafront Jazz Lounge",
    date: "July 02, 2026",
    time: "19:30 - 22:30",
    venue: "Red Sea Corniche Amphitheatre",
    price: "SAR 200",
    availableTickets: 42,
    description: "Cool sea breeze, local acoustic fusion, and iconic saxophone rhythms perfectly crafted for a warm summer night under the stars.",
  },
  {
    id: "concert-3",
    title: "Al-Ula Heritage Acoustic Nights",
    date: "August 12, 2026",
    time: "21:00 - 01:00",
    venue: "Maraya Concert Hall, Al-Ula",
    price: "SAR 450",
    availableTickets: 12,
    description: "A highly exclusive acoustic session inside the world's largest mirrored building, surrounded by illuminated ancient desert canyons.",
  },
];
